name: Build and Push Docker image

on:
  push:
    branches:
      - main
     
  pull_request:
    types: [closed]
    branches:
      - main
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Docker_hub # << coloque o nome exato do ambiente do Environment
  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get repo name
        id: vars
        run: |
          REPO=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}')
          echo "repo=$REPO" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.vars.outputs.repo }}:latest
